finalWork/final/urls.py
from django.conf.urls import url
from final import views


urlpatterns = [
    url(r'^index/', views.index, name='my_index'),
    url(r'^movies/', views.movie, name='my_movies'),
    url('phones/', views.phone, name='my_phones'),
    url('houses/', views.house, name='my_houses'),
    url('articles/', views.article, name='my_articles'),
]

finalWork/finalWork/urls.py
from django.conf.urls import url,include
from django.contrib import admin


urlpatterns = [
    url(r'^final/', include(('final.urls'),namespace='final_app')),
]

finalWork/lib/urls.py
from django.conf.urls import url
from lib import views


urlpatterns = [
    url('index/', views.index, name='index'),
    url('test',views.test),
    url('table/',views.detail, name='detail')
]

finalWork/mine/urls.py
from django.conf.urls import url
from mine import views


urlpatterns = [
    url('index/', views.index, name='index'),
    url('test',views.test),
    url('table/',views.detail, name='detail')
]

finalWork/web/urls.py
from django.conf.urls import url
from lib import views


urlpatterns = [
    url('movies/', views.index, name='index'),
    url('phones/', views.index, name='phones'),
    url('houses/', views.index, name='houses'),
    url('articles/', views.index, name='articles'),
]

finalWork/final/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class Doubanmoviesall(models.Model):
    field_id = models.AutoField(db_column='_id', primary_key=True)  # Field renamed because it started with '_'.
    directors = models.CharField(max_length=1000, blank=True, null=True)
    rate = models.CharField(max_length=500, blank=True, null=True)
    cover_x = models.IntegerField(blank=True, null=True)
    star = models.CharField(max_length=50, blank=True, null=True)
    title = models.CharField(max_length=100, blank=True, null=True)
    url = models.CharField(max_length=250, blank=True, null=True)
    casts = models.CharField(max_length=250, blank=True, null=True)
    cover = models.CharField(max_length=250, blank=True, null=True)
    id = models.CharField(max_length=100, blank=True, null=True)
    cover_y = models.IntegerField(blank=True, null=True)

class Phonejd(models.Model):
    phone_link = models.CharField(max_length=255, blank=True, null=True)
    phone_name = models.CharField(max_length=255, blank=True, null=True)
    phone_price = models.CharField(max_length=255, blank=True, null=True)
    phone_commits = models.CharField(max_length=255, blank=True, null=True)
    shop_name = models.CharField(max_length=255, blank=True, null=True)



class House(models.Model):
    title = models.CharField(max_length=255, blank=True, null=True)
    address = models.CharField(max_length=255, blank=True, null=True)
    price = models.CharField(max_length=255, blank=True, null=True)
    url = models.CharField(max_length=3000, blank=True, null=True)

class Wechatessays(models.Model):
    title = models.CharField(max_length=255, blank=True, null=True)
    txt_info = models.CharField(max_length=255, blank=True, null=True)
    account = models.CharField(max_length=255, blank=True, null=True)
    url = models.CharField(max_length=3000, blank=True, null=True)

finalWork/lib/models.py
# -*- coding: utf-8 -*-
from django.db import models

# Create your models here.
from django.db import models
class Moviesdouban(models.Model):
    field_id = models.AutoField(db_column='_id', primary_key=True)  # Field renamed because it started with '_'.
    directors = models.CharField(max_length=1000, blank=True, null=True)
    rate = models.CharField(max_length=500, blank=True, null=True)
    cover_x = models.IntegerField(blank=True, null=True)
    star = models.CharField(max_length=50, blank=True, null=True)
    title = models.CharField(max_length=100, blank=True, null=True)
    url = models.CharField(max_length=250, blank=True, null=True)
    casts = models.CharField(max_length=250, blank=True, null=True)
    cover = models.CharField(max_length=250, blank=True, null=True)
    id = models.CharField(max_length=100, blank=True, null=True)
    cover_y = models.IntegerField(blank=True, null=True)

finalWork/mine/models.py
# -*- coding: utf-8 -*-
from django.db import models

# Create your models here.
from django.db import models
class Moviesdouban(models.Model):
    field_id = models.AutoField(db_column='_id', primary_key=True)  # Field renamed because it started with '_'.
    directors = models.CharField(max_length=1000, blank=True, null=True)
    rate = models.CharField(max_length=500, blank=True, null=True)
    cover_x = models.IntegerField(blank=True, null=True)
    star = models.CharField(max_length=50, blank=True, null=True)
    title = models.CharField(max_length=100, blank=True, null=True)
    url = models.CharField(max_length=250, blank=True, null=True)
    casts = models.CharField(max_length=250, blank=True, null=True)
    cover = models.CharField(max_length=250, blank=True, null=True)
    id = models.CharField(max_length=100, blank=True, null=True)
    cover_y = models.IntegerField(blank=True, null=True)

finalWork/web/models.py
# -*- coding: utf-8 -*-
from django.db import models

# Create your models here.
from django.db import models
class Moviesdouban(models.Model):
    field_id = models.AutoField(db_column='_id', primary_key=True)  # Field renamed because it started with '_'.
    directors = models.CharField(max_length=1000, blank=True, null=True)
    rate = models.CharField(max_length=500, blank=True, null=True)
    cover_x = models.IntegerField(blank=True, null=True)
    star = models.CharField(max_length=50, blank=True, null=True)
    title = models.CharField(max_length=100, blank=True, null=True)
    url = models.CharField(max_length=250, blank=True, null=True)
    casts = models.CharField(max_length=250, blank=True, null=True)
    cover = models.CharField(max_length=250, blank=True, null=True)
    id = models.CharField(max_length=100, blank=True, null=True)
    cover_y = models.IntegerField(blank=True, null=True)

finalWork/final/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from final.models import Doubanmoviesall,Phonejd,House,Wechatessays
from django.http import HttpResponse,HttpResponseRedirect

from django.shortcuts import render

# Create your views here.
from django.shortcuts import render


# Create your views here.

def index(request):
    return render(request, 'index_.html')

def movie(request):
    movies_list=Doubanmoviesall.objects.all()
    context={'movielist':movies_list}
    print(context)
    return render(request,'movies.html',context)

def phone(request):
    phone_list=Phonejd.objects.all()
    context={'phonelist':phone_list}
    print(context)
    return render(request,'phones.html',context)

def house(request):
    house_list=House.objects.all()
    context={'houselist':house_list}
    print(context)
    return render(request,'houses.html',context)

def article(request):
    articles_list=Wechatessays.objects.all()
    context={'articlelist':articles_list}
    print(context)
    return render(request,'articles.html',context)

finalWork/lib/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from lib.models import Moviesdouban

from django.shortcuts import render

# Create your views here.
from django.shortcuts import render


# Create your views here.
def index(request):
    return render(request, 'index_.html')


def test(request):
    return render(request, 'test.html')

def detail(request):
    movies_list=Moviesdouban.objects.all()
    context={'movielist':movies_list}
    print(context)
    return render(request,'detail.html',context)

finalWork/mine/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from mine.models import Moviesdouban

from django.shortcuts import render

# Create your views here.
from django.shortcuts import render


# Create your views here.
def index(request):
    return render(request, 'index.html')


def test(request):
    return render(request, 'test.html')

def detail(request):
    movies_list=Moviesdouban.objects.all()
    context={'movielist':movies_list}
    print(context)
    return render(request,'table.html',context)

finalWork/web/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from lib.models import Moviesdouban

from django.shortcuts import render

# Create your views here.
from django.shortcuts import render


# Create your views here.
def index(request):
    return render(request, 'index.html')


def test(request):
    return render(request, 'test.html')

def detail(request):
    movies_list=Moviesdouban.objects.all()
    context={'movielist':movies_list}
    print(context)
    return render(request,'detail.html',context)

finalWork/templates/articles.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" type="text/css" href="\static\css\table.css">
    <link rel="stylesheet" type="text/css" href="\static\css\layui.css">
    <script type="text/javascript" src="/static/js/jquery.min.js"></script>

    <style>
        .layui-input-block{
            width: 300px;
            float: left;
            margin-left: 0;
        }

        td.on{
            border-bottom: 1px solid #4FC3A1;
            color: #4FC3A1;
        }
        td.active{
            background: #4FC3A1;
            color: #fff;
        }
        .search_div{
            margin-left: 50px;
            position: fixed;
            left: 5px;
            top: 5px;
            background-color: #fff;
  }

    </style>
</head>
<body>
<div class="search_div">
  <form class="layui-form" action="" onSubmit="return search();">
    <div class="layui-form-item">
      <label class="layui-form-label">输入关键字</label>
      <div class="layui-input-block">
        <input type="text" name="title" required  lay-verify="required" placeholder="请输入关键字" autocomplete="off" class="layui-input" id="searchInput" value="">
      </div>
      <div class="layui-input-block">
        <button class="layui-btn" lay-submit lay-filter="formDemo">搜索</button>
      </div>
    </div>
  </form>
</div>
<div class="table-wrapper" style="margin-top: 80px">
    <table class="fl-table" id="all_list">

    <thead style="background: bisque">
    <tr>
        <th style="width: 100px">标题</th>
        <th>内容简介</th>
        <th>作者</th>
        <th>文章链接</th>
    </tr>
    </thead>
    <tbody>
    {% for article in articlelist %}
    <tr>
        <td class="list_one">{{ article.title }}</td>
        <td class="list_one">{{ article.txt_info }}</td>
        <td class="list_one">{{ article.account }}</td>
        <td class="">{{ article.url }}</td>
    </tr>
    {% endfor %}
    </tbody>
    </table>
</div>
<script>
    var active = 0;
  $('.ayui-btn').click(function(){
      alert("llll");
  })
  function search(){
    // 获取搜索框的值
    var kwds = $("#searchInput").val();
    // 获取第一个列表内容
    var this_one = {};
    var real_name = '';
    // 定义数据列表
    var list = $("#all_list .list_one");
    // 定义查找的起始值
    var true_one = 0;
    for (var i = 0; i < list.length; i++) {
      this_one = $(list[i]);

      real_name = this_one.text().toString();
      // 执行like匹配
      if(real_name.match(kwds)){
        // 处理第当前的结果
        if(true_one == active){
          // 获取窗口的宽和高
          var windows_wdh = $(window).width();
          var windows_hgt = $(window).height();
          // 获取第一个坐标
          var x_len = this_one.offset().left;
          var y_len = this_one.offset().top;
          // 驱动滚动条滚动到指定的位置
          $("html,body").animate({scrollTop:(y_len-windows_hgt/2), scrollLeft:(x_len-windows_wdh/2)},500);
          // 标记当前选中的结果
          this_one.addClass('active');
          this_one.removeClass('on');
        }else{
          // 标记符合的结果
          this_one.addClass('on');
          this_one.removeClass('active');
        }
        // 累加真实的选择
        true_one++;
      }else{
        this_one.removeClass('on');
      }
    }
    // 判断是否搜索完毕 如果搜索完毕 则从第一个开始 否则继续搜索下一个
    active = active >= true_one-1 ? 0 : active+1;

    return false;
  }
</script>
</body>
</html>

finalWork/templates/houses.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" type="text/css" href="\static\css\table.css">
    <link rel="stylesheet" type="text/css" href="\static\css\layui.css">
    <script type="text/javascript" src="/static/js/jquery.min.js"></script>

    <style>
        .layui-input-block{
            width: 300px;
            float: left;
            margin-left: 0;
        }

        td.on{
            border-bottom: 1px solid #4FC3A1;
            color: #4FC3A1;
        }
        td.active{
            background: #4FC3A1;
            color: #fff;
        }
        .search_div{
            margin-left: 50px;
            position: fixed;
            left: 5px;
            top: 5px;
            background-color: #fff;
  }

    </style>
</head>
<body>
<div class="search_div">
  <form class="layui-form" action="" onSubmit="return search();">
    <div class="layui-form-item">
      <label class="layui-form-label">输入关键字</label>
      <div class="layui-input-block">
        <input type="text" name="title" required  lay-verify="required" placeholder="请输入关键字" autocomplete="off" class="layui-input" id="searchInput" value="">
      </div>
      <div class="layui-input-block">
        <button class="layui-btn" lay-submit lay-filter="formDemo">搜索</button>
      </div>
    </div>
  </form>
</div>
<div class="table-wrapper" style="margin-top: 80px">
    <table class="fl-table" id="all_list">

    <thead style="background: bisque">
    <tr>
        <th style="width: 100px">标题</th>
        <th>地址</th>
        <th>价格</th>
        <th><a>链接</a></th>
    </tr>
    </thead>
    <tbody>
    {% for house in houselist %}
    <tr>
        <td class="list_one">{{ house.title }}</td>
        <td class="list_one">{{ house.address }}</td>
        <td class="list_one">{{ house.price }}</td>
        <td style="float: left">{{ house.url }}</td>
    </tr>
    {% endfor %}
    </tbody>
    </table>
</div>

<script>
    var active = 0;
  $('.ayui-btn').click(function(){
      alert("llll");
  })
  function search(){
    // 获取搜索框的值
    var kwds = $("#searchInput").val();
    // 获取第一个列表内容
    var this_one = {};
    var real_name = '';
    // 定义数据列表
    var list = $("#all_list .list_one");
    // 定义查找的起始值
    var true_one = 0;
    for (var i = 0; i < list.length; i++) {
      this_one = $(list[i]);

      real_name = this_one.text().toString();
      // 执行like匹配
      if(real_name.match(kwds)){
        // 处理第当前的结果
        if(true_one == active){
          // 获取窗口的宽和高
          var windows_wdh = $(window).width();
          var windows_hgt = $(window).height();
          // 获取第一个坐标
          var x_len = this_one.offset().left;
          var y_len = this_one.offset().top;
          // 驱动滚动条滚动到指定的位置
          $("html,body").animate({scrollTop:(y_len-windows_hgt/2), scrollLeft:(x_len-windows_wdh/2)},500);
          // 标记当前选中的结果
          this_one.addClass('active');
          this_one.removeClass('on');
        }else{
          // 标记符合的结果
          this_one.addClass('on');
          this_one.removeClass('active');
        }
        // 累加真实的选择
        true_one++;
      }else{
        this_one.removeClass('on');
      }
    }
    // 判断是否搜索完毕 如果搜索完毕 则从第一个开始 否则继续搜索下一个
    active = active >= true_one-1 ? 0 : active+1;

    return false;
  }
</script>
</body>
</html>

finalWork/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" type="text/css" href="\static\css\style.css">
</head>
<body>
<div class="container">
    <header class="title">
        <h1>myWeb</h1>
    </header>
    <div class="main">
        <div class="side">
            <nav class="side_menu">
                <div class="side_trigger"><span class="side_icon side_icon_menu"></span><a class="side_label">Menu</a></div>
                <ul class="menu_ul" data-id="all">
                    <li class="movie" id="m" data-id="movie"><a class="side_icon side_icon_1">page1</a></li>
                    <li class="second" data-id="movie"><a class="side_icon side_icon_2">page2</a></li>
                    <li class="third" data-id="movie"><a class="side_icon side_icon_3">page3</a></li>
                    <li class="forth"><a class="side_icon side_icon_4">page4</a></li>
                    <li class="fifth"><a class="side_icon side_icon_5">page5</a></li>
                </ul>
            </nav>
        </div>
        <div class="content">
            <div id="p1" class="d1" style="display: contents">d1</div>
            <div class="d2" style="display: none">d2</div>
            <div class="d3" style="display: none">d3</div>
            <div class="d4" style="display: none">d4</div>
            <div class="d5" style="display: none">d5</div>
        </div>
    </div>


</div>
<script>
    var menu = (function() {
	function init() {

		[].slice.call( document.querySelectorAll( '.side_menu' ) ).forEach( function( el ) {

			var trigger = el.querySelector( 'div.side_trigger' ),
				icon = trigger.querySelector( 'span.side_icon_menu' ),
                c=el.querySelector('ul'),
				open = false;


			trigger.addEventListener( 'click', function( event ) {
				if( !open ) {
					el.className += ' side_menu_open';
					open = true;
				}
			}, false );


			first = document.querySelector('.movie').addEventListener('click', function() {
                x=document.getElementsByClassName('d1');
                //x.style.cssText='display:none;'
                //x.style.setProperty('display','none');
                alert(typeof (x));


            });

			second = document.querySelector('.second').addEventListener('click', function() {
                alert('here2');
            });

			third = document.querySelector('.third').addEventListener('click', function() {
                alert('here3');
            });

			forth = document.querySelector('.forth').addEventListener('click', function() {
                alert('here4');
            });

			fifth = document.querySelector('.fifth').addEventListener('click', function() {
                alert('here5');
            });

			icon.addEventListener( 'click', function( event ) {
				if( open ) {
					event.stopPropagation();
					open = false;
					el.className = el.className.replace(/\bside_menu_open\b/,'');
					return false;
				}
			}, false );

		} );

	}

	init();

})();


</script>

<script>
    x=document.getElementsByClassName('d1');
    x.style.setProperty('display','none');
</script>

</body>
</html>

finalWork/templates/index_.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" type="text/css" href="\static\css\style.css">
</head>
<body>
<div class="container" >
    <header class="title">
        <h1 style="font-max-size: xx-large">数据爬取</h1>
    </header>
    <div class="main" style="margin-left: 20px">
        <div class="side" style="min-width: 420px;margin-left: 0">
            <nav class="side_menu  side_menu_open">
                <ul class="menu_ul" data-id="all">
                    <li><a href="#d1" class="side_icon side_icon_1">豆瓣电影数据爬取</a></li>
                    <li><a href="#d2" class="side_icon side_icon_2">京东商城手机数据爬取</a></li>
                    <li><a href="#d3" class="side_icon side_icon_3">58同城品牌公寓数据爬取</a></li>
                    <li><a href="#d4" class="side_icon side_icon_4">搜狗微信公众号热门文章数据爬取</a></li>
                </ul>
            </nav>
        </div>
        <div class="tab_content"  style="padding-left: 20px;overflow: hidden;width: 500px;height: 500px;">
            <div id="d1" class="item" style="width: 100%;height: 100%;">
                <img src="/static/images/movie.png" style="margin-top:10px;width:auto;height:auto;max-width:100%;max-height:100%;">
                <a href="{% url 'final_app:my_movies' %}">前往电影数据页面</a>
            </div>
            <div id="d2" class="item" style="overflow: hidden;width: 100%;height: 100%;">
                <img src="/static/images/phone.png" style="margin-top:10px;width:auto;height:auto;max-width:100%;max-height:100%;">
                <a href="{% url 'final_app:my_phones' %}">前往手机数据页面</a>
            </div>
            <div id="d3" class="item" style="overflow: hidden;width: 100%;height: 100%;">
                <img src="/static/images/house.png" style="margin-top:10px;width:auto;height:auto;max-width:100%;max-height:100%;">
                <a href="{% url 'final_app:my_houses' %}">前往房子数据页面</a>
            </div>
            <div id="d4" class="item" style="overflow: hidden;width: 100%;height: 100%;">
                <img src="/static/images/article.png" style="margin-top:10px;width:auto;height:auto;max-width:100%;max-height:100%;">
                <a href="{% url 'final_app:my_articles' %}">前往文章数据页面</a>
            </div>
        </div>
    </div>


</div>


</body>
</html>

finalWork/templates/movie.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" type="text/css" href="\static\css\table.css">
</head>
<body>
<div class="search_div">
  <form class="layui-form" action="" onSubmit="return search();">
    <div class="layui-form-item">
      <label class="layui-form-label">输入关键字</label>
      <div class="layui-input-block">
        <input type="text" name="title" required  lay-verify="required" placeholder="请输入关键字" autocomplete="off" class="layui-input" id="searchInput" value="张">
      </div>
      <div class="layui-input-block">
        <button class="layui-btn" lay-submit lay-filter="formDemo">搜索</button>
      </div>
    </div>
  </form>
</div>
<div class="table-wrapper">
    <table class="fl-table" id="all_list">

    <thead style="background: bisque">
    <tr>
        <th>导演：</th>
        <th>电影名称</th>
        <th>豆瓣评分：</th>
        <th><a>链接：</a></th>
        <th>演员：</th>
        <th>图片：</th>
    </tr>
    </thead>
    <tbody>
    {% for movie in movielist %}
    <tr>
        <td class="list_one">{{ movie.directors }}</td>
        <td class="list_one">{{ movie.title }}</td>
        <td>{{ movie.rate }}</td>
        <td>{{ movie.url }}</td>
        <td class="list_one">{{ movie.casts }}</td>
        <td class="list_one">{{ movie.cover }}</td>
    </tr>
    {% endfor %}
    </tbody>
    </table>
</div>
</body>
</html>

finalWork/templates/movies.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" type="text/css" href="\static\css\table.css">
    <link rel="stylesheet" type="text/css" href="\static\css\layui.css">
    <script type="text/javascript" src="/static/js/jquery.min.js"></script>

    <style>
        .layui-input-block{
            width: 300px;
            float: left;
            margin-left: 0;
        }

        td.on{
            border-bottom: 1px solid #4FC3A1;
            color: #4FC3A1;
        }
        td.active{
            background: #4FC3A1;
            color: #fff;
        }
        .search_div{
            margin-left: 50px;
            position: fixed;
            left: 5px;
            top: 5px;
            background-color: #fff;
  }

    </style>
</head>
<body>
<div class="search_div">
  <form class="layui-form" action="" onSubmit="return search();">
    <div class="layui-form-item">
      <label class="layui-form-label">输入关键字</label>
      <div class="layui-input-block">
        <input type="text" name="title" required  lay-verify="required" placeholder="请输入关键字" autocomplete="off" class="layui-input" style="width: 300px" id="searchInput" value="">
      </div>
      <div class="layui-input-block">
        <button class="layui-btn" lay-submit lay-filter="formDemo">搜索</button>
      </div>
    </div>
  </form>
</div>
<div class="table-wrapper" style="margin-top: 80px">
    <table class="fl-table" id="all_list">

    <thead style="background: bisque">
    <tr>
        <th style="width: 100px">导演</th>
        <th>电影名称</th>
        <th>豆瓣评分</th>
        <th><a>链接</a></th>
        <th>演员</th>
        <th>图片</th>
    </tr>
    </thead>
    <tbody>
    {% for movie in movielist %}
    <tr>
        <td class="list_one">{{ movie.directors }}</td>
        <td class="list_one">{{ movie.title }}</td>
        <td>{{ movie.rate }}</td>
        <td>{{ movie.url }}</td>
        <td class="list_one">{{ movie.casts }}</td>
        <td class="list_one">{{ movie.cover }}</td>
    </tr>
    {% endfor %}
    </tbody>
    </table>
</div>
<script>
    var active = 0;
  $('.ayui-btn').click(function(){
      alert("llll");
  })
  function search(){
    // 获取搜索框的值
    var kwds = $("#searchInput").val();
    // 获取第一个列表内容
    var this_one = {};
    var real_name = '';
    // 定义数据列表
    var list = $("#all_list .list_one");
    // 定义查找的起始值
    var true_one = 0;
    for (var i = 0; i < list.length; i++) {
      this_one = $(list[i]);

      real_name = this_one.text().toString();
      // 执行like匹配
      if(real_name.match(kwds)){
        // 处理第当前的结果
        if(true_one == active){
          // 获取窗口的宽和高
          var windows_wdh = $(window).width();
          var windows_hgt = $(window).height();
          // 获取第一个坐标
          var x_len = this_one.offset().left;
          var y_len = this_one.offset().top;
          // 驱动滚动条滚动到指定的位置
          $("html,body").animate({scrollTop:(y_len-windows_hgt/2), scrollLeft:(x_len-windows_wdh/2)},500);
          // 标记当前选中的结果
          this_one.addClass('active');
          this_one.removeClass('on');
        }else{
          // 标记符合的结果
          this_one.addClass('on');
          this_one.removeClass('active');
        }
        // 累加真实的选择
        true_one++;
      }else{
        this_one.removeClass('on');
      }
    }
    // 判断是否搜索完毕 如果搜索完毕 则从第一个开始 否则继续搜索下一个
    active = active >= true_one-1 ? 0 : active+1;

    return false;
  }
</script>
</body>
</html>

finalWork/templates/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <style>
        ul,li{
  margin:0;
  padding:0;
  list-style:none;
}
.container{
  width:400px;
  height:300px;
  background-color:silver;
}
.tab-content{
  width:100%;
  height:80%;
  overflow:hidden;
}
.tab-content .item{
  width:100%;
  height:100%;
}
.tab-control{
  width:100%;
  height:20%;
}
.tab-control ul{
  height:100%;
}
.tab-control li{
  width:25%;
  height:100%;
  float:left;
  border:1px solid silver;
  box-sizing:border-box;
  background-color:white;
  cursor: pointer;
}
.tab-control li:hover{
  background-color:#7b7474
}
.tab-control a{
  display:inline-block;
  width:100%;
  height:100%;
  line-height:100%;
  text-align:center;
  text-decoration: none;
}
.tab-control a::after{
  content:"";
  display:inline-block;
  height:100%;
  vertical-align:middle;
}
.tab-content .item:target{
  background:yellow;
}
    </style>
</head>
<body>
<div class="container">
   <div class="tab-content">
     <div id="item1" class="item">内容1</div>
     <div id="item2" class="item">内容2</div>
     <div id="item3" class="item">内容3</div>
     <div id="item4" class="item">内容4</div>
   </div>
   <div class="tab-control">
       <nav>

           <ul>
        <li><a href="#item1">内容1</a></li>
        <li><a href="#item2">内容2</a></li>
        <li><a href="#item3">内容3</a></li>
        <li><a href="#item4">内容4</a></li>
     </ul>

       </nav>

   </div>
</div>

</body>
</html>